#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x52d0d115, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x52d9ff2d, __VMLINUX_SYMBOL_STR(register_netdevice) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x5f8d6aaa, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x8bc95480, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xa704aafa, __VMLINUX_SYMBOL_STR(register_pernet_device) },
	{ 0x7a69b0b8, __VMLINUX_SYMBOL_STR(__skb_gso_segment) },
	{ 0xadaabe1b, __VMLINUX_SYMBOL_STR(pv_lock_ops) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0x60bf3ee9, __VMLINUX_SYMBOL_STR(genl_unregister_family) },
	{ 0xa475c663, __VMLINUX_SYMBOL_STR(ip_local_out) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0x37adf311, __VMLINUX_SYMBOL_STR(netdev_rx_handler_register) },
	{ 0xc715d9e0, __VMLINUX_SYMBOL_STR(boot_cpu_data) },
	{ 0xc7a4fbed, __VMLINUX_SYMBOL_STR(rtnl_lock) },
	{ 0xff3b6900, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0x1637ff0f, __VMLINUX_SYMBOL_STR(_raw_spin_lock_bh) },
	{ 0x93bd97f9, __VMLINUX_SYMBOL_STR(skb_clone) },
	{ 0xae9d3a85, __VMLINUX_SYMBOL_STR(dev_get_by_name) },
	{ 0x9e379cd4, __VMLINUX_SYMBOL_STR(skb_copy) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0xd2da1048, __VMLINUX_SYMBOL_STR(register_netdevice_notifier) },
	{ 0x88bfa7e, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0x2c7036b0, __VMLINUX_SYMBOL_STR(netdev_master_upper_dev_get) },
	{ 0xf087137d, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x949f7342, __VMLINUX_SYMBOL_STR(__alloc_percpu) },
	{ 0x8bc8a169, __VMLINUX_SYMBOL_STR(inet_proto_csum_replace4) },
	{ 0x6fd6a16d, __VMLINUX_SYMBOL_STR(sock_create_kern) },
	{ 0xed93d7e9, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x846733a4, __VMLINUX_SYMBOL_STR(skb_tx_error) },
	{ 0x27000b29, __VMLINUX_SYMBOL_STR(crc32c) },
	{ 0x26653ef5, __VMLINUX_SYMBOL_STR(__put_net) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xc9ec4e21, __VMLINUX_SYMBOL_STR(free_percpu) },
	{ 0x9d0d6206, __VMLINUX_SYMBOL_STR(unregister_netdevice_notifier) },
	{ 0x5c27c764, __VMLINUX_SYMBOL_STR(skb_trim) },
	{ 0x8e60355d, __VMLINUX_SYMBOL_STR(inet_proto_csum_replace16) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xb52bd685, __VMLINUX_SYMBOL_STR(netdev_master_upper_dev_link) },
	{ 0x2ebc04eb, __VMLINUX_SYMBOL_STR(skb_copy_ubufs) },
	{ 0xbdece1ea, __VMLINUX_SYMBOL_STR(__netdev_alloc_skb) },
	{ 0xc1834e2f, __VMLINUX_SYMBOL_STR(netif_rx) },
	{ 0x30a6e31f, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xf1db1704, __VMLINUX_SYMBOL_STR(nla_memcpy) },
	{ 0x9148fa95, __VMLINUX_SYMBOL_STR(nlmsg_notify) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x45eae245, __VMLINUX_SYMBOL_STR(skb_checksum) },
	{ 0x8f64aa4, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x37befc70, __VMLINUX_SYMBOL_STR(jiffies_to_msecs) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xabdc4e37, __VMLINUX_SYMBOL_STR(ethtool_op_get_link) },
	{ 0xfc0d1ce6, __VMLINUX_SYMBOL_STR(__genl_register_family_with_ops) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x2d87aa98, __VMLINUX_SYMBOL_STR(unregister_pernet_device) },
	{ 0x99591a7a, __VMLINUX_SYMBOL_STR(ipv6_ext_hdr) },
	{ 0xd85bf35f, __VMLINUX_SYMBOL_STR(__skb_warn_lro_forwarding) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0xcd279169, __VMLINUX_SYMBOL_STR(nla_find) },
	{ 0x6ead33b, __VMLINUX_SYMBOL_STR(gre_cisco_unregister) },
	{ 0x6d17660f, __VMLINUX_SYMBOL_STR(free_netdev) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x83f40daf, __VMLINUX_SYMBOL_STR(nla_put) },
	{ 0xffe61d48, __VMLINUX_SYMBOL_STR(netdev_upper_dev_unlink) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x830c6c3b, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xb4a4b11a, __VMLINUX_SYMBOL_STR(skb_push) },
	{ 0xef1ac853, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x903e67ac, __VMLINUX_SYMBOL_STR(dev_get_by_index_rcu) },
	{ 0x99517682, __VMLINUX_SYMBOL_STR(udp_encap_enable) },
	{ 0x372f1a8a, __VMLINUX_SYMBOL_STR(__skb_get_rxhash) },
	{ 0x3e3ca997, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0xa5edb381, __VMLINUX_SYMBOL_STR(netlink_unicast) },
	{ 0xa735db59, __VMLINUX_SYMBOL_STR(prandom_u32) },
	{ 0x4fdf8251, __VMLINUX_SYMBOL_STR(skb_pull) },
	{ 0x217dda13, __VMLINUX_SYMBOL_STR(flex_array_get) },
	{ 0xfdace2a2, __VMLINUX_SYMBOL_STR(__get_page_tail) },
	{ 0x4ea5d10, __VMLINUX_SYMBOL_STR(ksize) },
	{ 0x3ff62317, __VMLINUX_SYMBOL_STR(local_bh_disable) },
	{ 0xe9eae9c6, __VMLINUX_SYMBOL_STR(__secpath_destroy) },
	{ 0xde1079c4, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xc9daba46, __VMLINUX_SYMBOL_STR(__alloc_skb) },
	{ 0x40fa4be5, __VMLINUX_SYMBOL_STR(sk_release_kernel) },
	{ 0xe7b6bd3b, __VMLINUX_SYMBOL_STR(ipv6_skip_exthdr) },
	{ 0x445738cf, __VMLINUX_SYMBOL_STR(netlink_broadcast) },
	{ 0xba63339c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_bh) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x4f391d0e, __VMLINUX_SYMBOL_STR(nla_parse) },
	{ 0xb9249d16, __VMLINUX_SYMBOL_STR(cpu_possible_mask) },
	{ 0x21c9b23d, __VMLINUX_SYMBOL_STR(netdev_rx_handler_unregister) },
	{ 0xded2a00, __VMLINUX_SYMBOL_STR(skb_checksum_help) },
	{ 0x70b2e407, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0x413bcf7c, __VMLINUX_SYMBOL_STR(gre_cisco_register) },
	{ 0x6b2dc060, __VMLINUX_SYMBOL_STR(dump_stack) },
	{ 0x799aca4, __VMLINUX_SYMBOL_STR(local_bh_enable) },
	{ 0x20df89d5, __VMLINUX_SYMBOL_STR(alloc_netdev_mqs) },
	{ 0x6c36a77e, __VMLINUX_SYMBOL_STR(eth_type_trans) },
	{ 0xbdb09834, __VMLINUX_SYMBOL_STR(pskb_expand_head) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xedcf026e, __VMLINUX_SYMBOL_STR(ether_setup) },
	{ 0xdab920b4, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xd52bf1ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x3928efe9, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0x9327f5ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x2a18c74, __VMLINUX_SYMBOL_STR(nf_conntrack_destroy) },
	{ 0x815b5a8c, __VMLINUX_SYMBOL_STR(skb_pull_rcsum) },
	{ 0x55023b4b, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x370a4517, __VMLINUX_SYMBOL_STR(unregister_netdevice_queue) },
	{ 0xdc220c88, __VMLINUX_SYMBOL_STR(ip_route_output_flow) },
	{ 0xce46e140, __VMLINUX_SYMBOL_STR(ktime_get_ts) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0xe38c3a67, __VMLINUX_SYMBOL_STR(netlink_set_err) },
	{ 0xe7722171, __VMLINUX_SYMBOL_STR(flex_array_free) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x3cfe0bec, __VMLINUX_SYMBOL_STR(dev_set_promiscuity) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xa75312bc, __VMLINUX_SYMBOL_STR(call_rcu_sched) },
	{ 0xa139f046, __VMLINUX_SYMBOL_STR(genlmsg_put) },
	{ 0x5a050dd4, __VMLINUX_SYMBOL_STR(kernel_bind) },
	{ 0xd6bb959d, __VMLINUX_SYMBOL_STR(genl_register_mc_group) },
	{ 0xd3dcab0b, __VMLINUX_SYMBOL_STR(flex_array_alloc) },
	{ 0x7628f3c7, __VMLINUX_SYMBOL_STR(this_cpu_off) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x4bf71d7, __VMLINUX_SYMBOL_STR(nla_reserve) },
	{ 0xb0e602eb, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0xe113bbbc, __VMLINUX_SYMBOL_STR(csum_partial) },
	{ 0x6ef6811b, __VMLINUX_SYMBOL_STR(consume_skb) },
	{ 0x85670f1d, __VMLINUX_SYMBOL_STR(rtnl_is_locked) },
	{ 0xd91af428, __VMLINUX_SYMBOL_STR(dev_queue_xmit) },
	{ 0x6f9d109, __VMLINUX_SYMBOL_STR(skb_put) },
	{ 0x7193ae99, __VMLINUX_SYMBOL_STR(eth_mac_addr) },
	{ 0xfa4250a1, __VMLINUX_SYMBOL_STR(skb_copy_bits) },
	{ 0x475100c2, __VMLINUX_SYMBOL_STR(inet_get_local_port_range) },
	{ 0x6e720ff2, __VMLINUX_SYMBOL_STR(rtnl_unlock) },
	{ 0x60cf56b5, __VMLINUX_SYMBOL_STR(__nla_put) },
	{ 0x1ec4eb34, __VMLINUX_SYMBOL_STR(flex_array_prealloc) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=libcrc32c,gre";


MODULE_INFO(srcversion, "43A9CD78B985DCE690763C0");
